// Package shot is the capture every rebuild shares.
//
// One place, because nine rebuilds each writing their own means nine slightly
// different ideas of what a screenshot is — and the point of the repository is
// that they are comparable.
package shot

import (
	"fmt"
	"os"
	"path/filepath"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/richarddavenport/tuikit/app"
	"github.com/richarddavenport/tuikit/comp"
	"github.com/richarddavenport/tuikit/docgen"
	"github.com/richarddavenport/tuikit/harness"
	"github.com/richarddavenport/tuikit/theme"
)

// State is one thing a rebuild can be showing.
type State struct {
	Name string
	Note string
	// Build returns a model already holding its world. It must not rely on
	// Init: harness.Press discards the tea.Cmd an Update returns, so nothing
	// asynchronous resolves during a capture. That is what makes a capture
	// deterministic — see tuikit issue 65.
	Build func() app.Model
}

// Size is the terminal every rebuild is captured at, so two rebuilds side by
// side are the same shape.
const (
	Width  = 132
	Height = 38
)

// Narrow is the second size, because most layout bugs are only visible when
// there is not enough room.
const (
	NarrowWidth  = 80
	NarrowHeight = 24
)

// Frame renders one state.
func Frame(s State, w, h int) string {
	return app.New(s.Build(), app.WithSize(w, h), app.WithChrome(theme.DefaultChrome)).View()
}

// Write captures every state to dir and builds a Markdown page beside it.
func Write(dir, title string, states []State) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for _, s := range states {
		frame := Frame(s, Width, Height)
		path := filepath.Join(dir, s.Name+".ansi")
		if err := os.WriteFile(path, []byte(frame), 0o600); err != nil {
			return err
		}
		svg := docgen.SVG(frame)
		if err := os.WriteFile(filepath.Join(dir, s.Name+".svg"), []byte(svg), 0o600); err != nil {
			return err
		}
	}
	return page(dir, title, states)
}

func page(dir, title string, states []State) error {
	body := fmt.Sprintf("# %s\n\nGenerated by `go run ./%s -shots`. Edit the capture, not this file.\n\n",
		title, filepath.Base(filepath.Dir(dir)))
	for _, s := range states {
		body += fmt.Sprintf("### %s\n\n%s\n\n![%s](frames/%s.svg)\n\n", s.Name, s.Note, s.Name, s.Name)
	}
	return os.WriteFile(filepath.Join(filepath.Dir(dir), "screens.md"), []byte(body), 0o600)
}

// Run opens a rebuild for real, so it can be driven by hand.
func Run(m app.Model) error {
	p := tea.NewProgram(
		app.New(m, app.WithChrome(theme.DefaultChrome), app.WithPixels(comp.Detect())),
		tea.WithAltScreen(), tea.WithMouseCellMotion())
	_, err := p.Run()
	return err
}

// Main is every rebuild's entry point: run it, or capture it.
func Main(name string, m func() app.Model, states []State) {
	if len(os.Args) > 1 && os.Args[1] == "-shots" {
		if err := shots(name, states); err != nil {
			fmt.Fprintln(os.Stderr, name+":", err)
			os.Exit(1)
		}
		return
	}
	if err := Run(m()); err != nil {
		fmt.Fprintln(os.Stderr, name+":", err)
		os.Exit(1)
	}
}

func shots(name string, states []State) error {
	dir := filepath.Join(name, "docs", "frames")
	if err := Write(dir, name+", screen by screen", states); err != nil {
		return err
	}
	fmt.Printf("wrote %s/docs/screens.md (%d frames)\n", name, len(states))
	return nil
}

// Goldens holds every state to a recorded frame, at both sizes, and checks the
// shape survives the color being stripped.
func Goldens(t harness.T, dir string, states []State) {
	for _, s := range states {
		harness.Golden(t, dir, s.Name, Frame(s, Width, Height))
		harness.Golden(t, filepath.Join(dir, "narrow"), s.Name, Frame(s, NarrowWidth, NarrowHeight))
		harness.ShapeSurvivesColor(t, s.Name, func() string { return Frame(s, Width, Height) })
	}
}
